
services:
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile-flask
      tags:
        - "thomastwyman557/ttwyman-flask-app-frontend"
    ports:
      - 80:5000
    depends_on:
      db:
        condition: service_healthy
    # volumes:
    #  - "./src/templates:/app/templates"
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app
        - action: rebuild
          path: ./src/requirements.txt

  db:
    build:
      context: ./src
      dockerfile: Dockerfile-postgres
      tags:
        - "thomastwyman557/ttwyman-flask-app-db"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "inventorydbuser", "-d", "inventorydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    build:
      context: .
      dockerfile_inline: |
        FROM adminer:latest
      tags:
        - "thomastwyman557/ttwyman-flask-app-admin"
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data:

