
services:
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile-flask
    image: ttwyman-flask-app-frontend
    ports:
      - 80:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ./src
      dockerfile: Dockerfile-postgres
    image: ttwyman-flask-app-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "inventorydbuser", "-d", "inventorydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:

