# syntax=docker/dockerfile:1

FROM postgres:16.4-alpine3.20 AS base

FROM base AS test
COPY /sql/* /docker-entrypoint-initdb.d/
VOLUME [ "/var/lib/postgresql/data" ]

FROM base AS prod
COPY /sql/* /docker-entrypoint-initdb.d/
VOLUME [ "/var/lib/postgresql/data" ]

